### PR TITLE
Issues 72,74

### PR DESCRIPTION
**Pull request by NicolasRouquette**

### CODE REVIEW

**Comment by castillr** [comment]
Issues #76 part of 0.9.0 scope?

**Comment by NicolasRouquette** [comment]
#76 is one of 8 issues in scope of 0.8.0.0; this PR is for 2 of the 8 only.

**Comment by castillr** [comment]
Lets setup "integration" branches based on the release scope so that we can better manage incremental additions like these.

**Comment by NicolasRouquette** [comment]
Created the branch integration/0.8.0.0

**Pull request closed without merging**
